### ISSUE TITLE
Question about RoPE

### ISSUE THREAD

**Issue by U-rara** [lucidrains/ring-attention-pytorch#15]
In the following code snippet (from [here](https://github.com/lucidrains/ring-attention-pytorch/blob/01962071ac13a1bf35fdca90b1e0bd70c660f313/ring_attention_pytorch/ring_attention.py#L409C13-L409C56)):
```
rotary_emb = self.rotary_embed(q.shape[-2])
```

Is the inference about the sequence length incorrect?

Based on [this line of code](https://github.com/lucidrains/ring-attention-pytorch/blob/01962071ac13a1bf35fdca90b1e0bd70c660f313/ring_attention_pytorch/ring_attention.py#L404):
```
q, k, v = rearrange(qkv, 'b n (h d) -> b n h d', d = self.dim_head).split(self.qkv_head_breakdown, dim = -2)
```
The `-2` dimension seems to be the number of heads. Shouldn't it be `q.shape[-3]`?

**Comment by lucidrains** [comment]
@U-rara great catch Wei!
