### ISSUE TITLE
Bug latest version

### ISSUE THREAD

**Issue by dwromero** [lucidrains/ring-attention-pytorch#21]
Hi @lucidrains,

there's a bug in the current version: 

https://github.com/lucidrains/ring-attention-pytorch/blob/main/ring_attention_pytorch/distributed.py#L76C12-L76C21

[rank1]:   File "/usr/local/lib/python3.10/dist-packages/ring_attention_pytorch/distributed.py", line 76, in all_gather_variable_dim
[rank1]:     mask = rearrange(mask, 'i j -> (i j)')
[rank1]: NameError: name 'rearrange' is not defined

**Comment by lucidrains** [comment]
@dwromero ah, nice catch, want to try the latest?
